/* Copy and labels: keep both language records in sync when editing. */
const translations = {
ar: {
name:'طارق إبراهيم عبدالله',shortName:'طارق إبراهيم',portfolio:'بورتفوليو المحتوى الرقمي',fieldTag:'المزرعة / المحتوى',title:'طارق إبراهيم | بورتفوليو المحتوى الرقمي والإنتاج الحيواني',description:'بورتفوليو تصوري يجمع بين الخبرة في الإنتاج الحيواني والمحتوى الرقمي والذكاء الاصطناعي.',
nav:['الرئيسية','نماذج المحتوى','الريل','الأفكار','عنّي'],menu:'فتح القائمة',closeMenu:'إغلاق القائمة',skip:'انتقل إلى المحتوى',language:'اختيار اللغة',label:'تصور لبورتفوليو السوشيال ميديا',application:'للتقديم على دور Social Media Specialist في مزرعتي',hero:'من الإنتاج الحيواني<br>إلى المحتوى الرقمي',intro:'أجمع بين الخبرة العملية في الإنتاج الحيواني، والخبرة في تطوير الويب والتصميم وتجربة المستخدم وأدوات الذكاء الاصطناعي، لصناعة محتوى رقمي يفهم المجال ويخاطب الجمهور بشكل أفضل.',explore:'شاهد نماذج المحتوى',viewReel:'شاهد نموذج الريل',heroTags:['معرفة بالمجال','تفكير بصري','أفكار قابلة للتنفيذ'],concept:'نموذج تصوري',visualTitle:'معلومة من المزرعة.<br>محتوى يستحق المشاركة.',visualSub:'معرفة حقيقية، في قالب رقمي واضح.',visualAlt:'عنصر بصري تصوري للمزرعة والمحتوى الرقمي، قابل للاستبدال بصورة مزرعة محلية',
fitTitle:'لماذا أرى أنني مناسب لهذا الدور؟',fitIntro:'معرفة بالمجال، ومهارات تساعدني على تقديمه للجمهور.',fit:[['خبرة حقيقية في المجال','لدي خبرة عملية في مزارع الألبان والإنتاج الحيواني، مما يساعدني على فهم المحتوى الفني وتقديمه بشكل صحيح ومبسط.'],['فهم بصري وتجربة مستخدم','خبرتي في Front-End وUI/UX تساعدني على تقديم المحتوى بصورة منظمة، واضحة، جذابة وسهلة الفهم.'],['استخدام أدوات الذكاء الاصطناعي','أستخدم أدوات AI في توليد الأفكار، تحسين النصوص، تخطيط المحتوى، وتجربة اتجاهات بصرية مختلفة بشكل أسرع.'],['تحويل المعرفة إلى محتوى','أستطيع تحويل المعلومة الفنية في الإنتاج الحيواني إلى Reel أو Post أو Story مفيدة وقابلة للمشاركة.']],
samplesTitle:'نماذج محتوى',samplesIntro:'أربع أفكار تربط المعلومة الفنية باحتياج الجمهور. نماذج مستقلة للتقديم، وليست منشورات رسمية لمزرعتي.',format:'الشكل',objective:'الهدف',caption:'نص المنشور',action:'دعوة للتفاعل',sampleLabel:'نموذج منشور',
posts:[
{title:'3 علامات للإجهاد الحراري عند الأبقار',lead:'ارتفاع درجات الحرارة قد يؤثر بشكل مباشر على صحة الحيوان وإنتاج اللبن.',pre:'راقب العلامات التالية:',list:['زيادة معدل التنفس','انخفاض استهلاك العلف','انخفاض إنتاج اللبن'],end:'التدخل المبكر يساعد في تقليل التأثير والحفاظ على صحة القطيع.',format:'كاروسيل تعليمي',objective:'التوعية / التعليم',cta:'احفظ البوست وشاركه مع المهتمين بالإنتاج الحيواني.',cover:'راقب العلامات.<br>احمِ القطيع.',coverSub:'التنفس • العلف • إنتاج اللبن',tag:'رعاية القطيع',alt:'قالب تعليمي محلي عن ثلاث علامات للإجهاد الحراري عند الأبقار'},
{title:'يوم في المزرعة',lead:'من بداية اليوم وحتى نهاية الحلب، كل خطوة داخل المزرعة لها دور في جودة الإنتاج وصحة القطيع.',pre:'يمكن أن يعرض المحتوى:',list:['التجهيز للحلب','رعاية الحيوانات','النظافة والتعقيم','متابعة الإنتاج'],end:'',format:'ريل / من خلف الكواليس',objective:'الثقة + التفاعل',cta:'تابعنا لمشاهدة المزيد من داخل المزرعة.',cover:'يوم يبدأ مبكرًا.<br>جودة في كل خطوة.',coverSub:'من داخل المزرعة',tag:'خلف الكواليس',alt:'قالب محلي ليوم في المزرعة، يستبدل بصورة حقيقية من المحلب'},
{title:'هل تعرف لماذا نظافة الضرع مهمة؟',lead:'النظافة الجيدة قبل وبعد الحلب ليست مجرد إجراء روتيني، بل جزء أساسي من:',pre:'',list:['تقليل فرص التهاب الضرع','تحسين جودة اللبن','حماية صحة الحيوان'],end:'',format:'منشور ثابت / كاروسيل',objective:'التعليم',cta:'ما أهم خطوة في روتين الحلب من وجهة نظرك؟',cover:'نظافة أفضل.<br>جودة أفضل.',coverSub:'قبل الحلب وبعده',tag:'جودة اللبن',alt:'قالب محلي توعوي عن نظافة الضرع وجودة اللبن'},
{title:'معلومة سريعة',lead:'انخفاض إنتاج اللبن لا يعني دائمًا وجود سبب واحد.',pre:'قد يكون السبب:',list:['التغذية','الإجهاد الحراري','الحالة الصحية','التغيرات في دورة الإنتاج'],end:'المتابعة المستمرة تساعد على اكتشاف السبب الحقيقي مبكرًا.',format:'منشور معلومة سريعة',objective:'التفاعل + التعليم',cta:'احفظ المعلومة للرجوع لها لاحقًا.',cover:'الإنتاج انخفض؟<br>انظر للصورة كاملة.',coverSub:'تغذية • بيئة • صحة • دورة إنتاج',tag:'معلومة سريعة',alt:'قالب محلي لمعلومة عن أسباب انخفاض إنتاج اللبن'}],
reelTitle:'نموذج Reel باستخدام الذكاء الاصطناعي',reelIntro:'فكرة، افتتاحية، وتسلسل بصري يحكي قصة الجودة في أقل من نصف دقيقة.',reelName:'من المزرعة إلى كوب اللبن في 30 ثانية',hook:'كوب اللبن اللي قدامك بدأ رحلته من هنا...',duration:'20–30 ثانية',aiLabel:'نموذج تم إنشاؤه بمساعدة أدوات الذكاء الاصطناعي',previewNote:'معاينة متحركة للستوري بورد؛ ليست فيديو نهائيًا.',play:'شغّل معاينة الريل',close:'إغلاق المعاينة',pause:'إيقاف مؤقت',resume:'استكمال',replay:'إعادة المعاينة',scene:'المشهد',promptTitle:'مثال للأمر المستخدم مع أدوات AI',scenes:[['مزرعة ألبان في الصباح الباكر','اليوم يبدأ بدري...'],['الأبقار تتجه إلى منطقة الحلب','رعاية ومتابعة مستمرة'],['التنظيف والعناية بالنظافة','النظافة جزء أساسي من الجودة'],['عملية الحلب','كل خطوة محسوبة'],['تبريد اللبن وتخزينه','الحفاظ على الجودة لا يتوقف بعد الحلب'],['إطار ختامي بأسلوب العلامة','من المزرعة... بجودة نثق بها']],reelAlt:'لوحة محلية لمعاينة الستوري بورد، تستبدل بإطار صباحي من مزرعة ألبان',
storiesTitle:'أفكار Stories',storiesIntro:'مساحة لمشاركة الجمهور: سؤال بسيط، اختيار سريع، وحوار مفيد.',stories:[['صح أم خطأ؟','زيادة معدل التنفس قد تكون علامة على الإجهاد الحراري.',['صح','خطأ']],['أي نوع محتوى تفضل؟','اختر ما تحب أن تشاهده أكثر.',['نصائح تربية','يوميات المزرعة']],['اسألنا أي سؤال عن رعاية الأبقار','ابدأ سؤالك هنا…',[]]],answerTrue:'إجابة صحيحة. زيادة معدل التنفس قد تكون إحدى علامات الإجهاد الحراري.',answerFalse:'الإجابة: صح. معدل التنفس أحد المؤشرات التي تستحق المتابعة.',vote:'تم اختيارك في هذا النموذج.',questionPlaceholder:'اكتب سؤالك…',send:'اعرض السؤال',questionEmpty:'اكتب سؤالًا أولًا.',questionSaved:'ظهر سؤالك في المعاينة فقط؛ لم يُرسل إلى أي جهة.',storyAlt:'خلفية محلية قابلة للاستبدال لصورة Story',
strategyTitle:'تصور مقترح لمحتوى مزرعتي',strategyIntro:'خمس ركائز لمحتوى مفيد ومتوازن؛ نقطة بداية يمكن تطويرها وفق أهداف الفريق والجمهور.',pillars:[['محتوى تعليمي',['نصائح رعاية','علامات مبكرة للمشكلات الصحية','التغذية والرعاية']],['من داخل المزرعة',['يوم في المزرعة','خلف الكواليس','مراحل الإنتاج']],['Reels قصيرة',['معلومة في 20 ثانية','خطأ شائع','سؤال وجواب سريع']],['محتوى تفاعلي',['استطلاع رأي','سؤال الأسبوع','صح أم خطأ']],['الثقة والمصداقية',['فريق العمل','أطباء ومهندسون','جودة الإنتاج','قصص من المزرعة']]],calendarTitle:'خطة محتوى أسبوعية',calendarIntro:'إيقاع مقترح يوازن بين التعليم، التفاعل، وبناء الثقة.',days:[['السبت','بوست تعليمي'],['الأحد','استطلاع Story'],['الاثنين','ريل من خلف الكواليس'],['الثلاثاء','معلومة سريعة'],['الأربعاء','Story سؤال وجواب'],['الخميس','كاروسيل تعليمي'],['الجمعة','محتوى مجتمعي / خفيف']],skillsTitle:'المهارات التي أضيفها للدور',skillsIntro:'أدوات تخدم الفكرة، من فهم المعلومة إلى تقديمها بصريًا.',skills:['فهم عملي للإنتاج الحيواني','تبسيط المحتوى الفني','UI/UX','GIMP','استخدام أدوات الذكاء الاصطناعي','أفكار المحتوى','المحتوى البصري','HTML / CSS / JavaScript','التصميم المتجاوب','Git / GitHub'],
aboutTitle:'عنّي',about:['أنا خريج إنتاج حيواني ولدي خبرة عملية في مزارع الألبان وإدارة المحلب ومتابعة صحة القطيع وجودة الإنتاج. انتقلت بعد ذلك للعمل في تطوير الويب، واكتسبت خبرة في تصميم الواجهات وتجربة المستخدم والمحتوى الرقمي وأدوات الذكاء الاصطناعي.','أرى أن الجمع بين فهم المجال الزراعي والمهارات الرقمية يمكن أن يساعدني على تقديم محتوى سوشيال ميديا أكثر دقة، جاذبية وقربًا من الجمهور المستهدف.'],honest:'هذا ملف أعمال تصوري يوضح مهاراتي القابلة للنقل إلى الدور، ولا يدّعي خبرة وظيفية سابقة بعنوان Social Media Specialist.',profileAlt:'مكان مخصص لإضافة صورة شخصية لطارق إبراهيم عبدالله',profileLabel:'إنتاج حيواني × محتوى رقمي',finalTitle:'أفهم المجال... وأمتلك الأدوات الرقمية لتقديمه بشكل مختلف.',finalSub:'هذا البورتفوليو نموذج عملي يوضح كيف يمكنني توظيف خبرتي في الإنتاج الحيواني والويب والـAI في صناعة محتوى رقمي مناسب لمزرعتي.',contact:'تواصل معي',contactPending:'سيُضاف البريد الإلكتروني قريبًا. بيانات التواصل لم تُضف بعد.',disclaimer:'هذا نموذج تصوري غير رسمي تم إعداده خصيصًا للتقديم على وظيفة في مزرعتي، وليس عملًا رسميًا تابعًا للشركة.',footer:'طارق إبراهيم عبدالله · بورتفوليو تصوري',back:'العودة للأعلى'
},
en: {
name:'Tarek Ibrahim Abdullah',shortName:'Tarek Ibrahim',portfolio:'Digital Content Portfolio',fieldTag:'FIELD / FEED',title:'Tarek Ibrahim | Digital Content & Animal Production Portfolio',description:'A concept portfolio combining practical animal production experience with digital content, design, and AI tools.',nav:['Home','Content','Reel','Ideas','About'],menu:'Open navigation',closeMenu:'Close navigation',skip:'Skip to content',language:'Choose language',label:'Social Media Portfolio Concept',application:'Application for a Social Media Specialist role at Mazraaty',hero:'From Animal Production<br>to Digital Content',intro:'I combine practical experience in animal production with web development, UI/UX, visual design, and AI tools to create digital content that understands the industry and communicates effectively with its audience.',explore:'Explore Content Samples',viewReel:'View Reel Concept',heroTags:['Industry knowledge','Visual thinking','Actionable ideas'],concept:'Concept sample',visualTitle:'Knowledge from the farm.<br>Content worth sharing.',visualSub:'Real understanding. Clear digital storytelling.',visualAlt:'Replaceable local visual placeholder for farm and digital content imagery',fitTitle:'Why I Believe I Am a Good Fit',fitIntro:'Industry understanding, with the skills to communicate it.',fit:[['Real Industry Experience','My hands-on experience in dairy farming and animal production helps me understand technical topics and turn them into accurate, easy-to-understand content.'],['Visual & UX Understanding','My Front-End and UI/UX background helps me create content that is structured, clear, visually appealing, and easy to understand.'],['Effective Use of AI Tools','I use AI tools for ideation, copy improvement, content planning, and exploring visual directions efficiently.'],['Turning Knowledge into Content','I can turn technical animal-production knowledge into useful and shareable Reels, Posts, and Stories.']],samplesTitle:'Content Samples',samplesIntro:'Four ideas that connect technical knowledge with audience needs. Independent application concepts, not official Mazraaty posts.',format:'Format',objective:'Objective',caption:'Post caption',action:'Call to action',sampleLabel:'Post concept',
posts:[
{title:'3 Signs of Heat Stress in Dairy Cows',lead:'High temperatures can directly affect animal health and milk production.',pre:'Watch for:',list:['Increased breathing rate','Reduced feed intake','Lower milk production'],end:'Early action can help reduce the impact and protect herd health.',format:'Educational Carousel',objective:'Awareness / Education',cta:'Save this post and share it with someone interested in animal production.',cover:'Watch the signs.<br>Protect the herd.',coverSub:'Breathing • Feed • Milk production',tag:'Herd care',alt:'Local educational placeholder about three signs of heat stress in dairy cows'},
{title:'A Day at the Farm',lead:'From the beginning of the day to the end of milking, every step plays a role in production quality and herd health.',pre:'This type of content can highlight:',list:['Milking preparation','Animal care','Hygiene and sanitation','Production monitoring'],end:'',format:'Reel / Behind the Scenes',objective:'Trust + Engagement',cta:'Follow for more behind-the-scenes farm content.',cover:'An early start.<br>Care in every step.',coverSub:'Inside the farm',tag:'Behind the scenes',alt:'Local farm-life placeholder to replace with an authentic milking-area photograph'},
{title:'Why Is Udder Hygiene So Important?',lead:'Good hygiene before and after milking is more than a routine procedure.',pre:'It plays an important role in:',list:['Reducing the risk of mastitis','Improving milk quality','Protecting animal health'],end:'',format:'Static Post / Carousel',objective:'Education',cta:'What do you think is the most important step in the milking routine?',cover:'Better hygiene.<br>Better quality.',coverSub:'Before and after milking',tag:'Milk quality',alt:'Local educational placeholder about udder hygiene and milk quality'},
{title:'Quick Tip',lead:'A drop in milk production does not always have one single cause.',pre:'Possible reasons include:',list:['Nutrition','Heat stress','Health condition','Changes in production cycle'],end:'Continuous monitoring helps identify the real cause early.',format:'Quick Tip Post',objective:'Engagement + Education',cta:'Save this tip for later.',cover:'Milk yield down?<br>See the whole picture.',coverSub:'Nutrition • Environment • Health • Cycle',tag:'Quick tip',alt:'Local quick-tip placeholder about causes of reduced milk production'}],
reelTitle:'AI-Assisted Reel Concept',reelIntro:'An idea, an opening hook, and a visual sequence telling a quality story in under half a minute.',reelName:'From the Farm to Your Glass in 30 Seconds',hook:'The glass of milk in front of you started its journey here...',duration:'20–30 seconds',aiLabel:'AI-Assisted Concept',previewNote:'Animated storyboard preview; not a finished video.',play:'Play reel preview',close:'Close preview',pause:'Pause',resume:'Resume',replay:'Replay preview',scene:'Scene',promptTitle:'Example AI prompt',scenes:[['Early morning dairy farm','The day starts early...'],['Cows moving toward the milking area','Continuous care and monitoring'],['Cleaning and hygiene','Hygiene is part of quality'],['Milking process','Every step matters'],['Milk cooling and storage','Quality does not stop after milking'],['Final brand-style frame','From the farm... with quality you can trust']],reelAlt:'Local storyboard placeholder to replace with an early morning dairy farm frame',storiesTitle:'Instagram Story Ideas',storiesIntro:'A space for the audience: a simple question, a quick choice, and a useful conversation.',stories:[['True or False?','An increased breathing rate can be a sign of heat stress.',['True','False']],['Which type of content do you prefer?','Choose what you would like to see more of.',['Animal Care Tips','Farm Life']],['Ask us anything about dairy cow care','Start your question here…',[]]],answerTrue:'Correct. Increased breathing can be one sign of heat stress.',answerFalse:'The answer is True. Breathing rate is one indicator worth monitoring.',vote:'Your choice is selected in this concept.',questionPlaceholder:'Write your question…',send:'Preview question',questionEmpty:'Write a question first.',questionSaved:'Your question appears only in this preview; it was not sent anywhere.',storyAlt:'Replaceable local Story background placeholder',
strategyTitle:'Proposed Content Direction for Mazraaty',strategyIntro:'Five pillars for useful, balanced content. A starting point to adapt to team goals and audience needs.',pillars:[['Educational Content',['Animal care tips','Early health warning signs','Feeding and management']],['Inside the Farm',['A day at the farm','Behind the scenes','Production stages']],['Short-Form Reels',['A tip in 20 seconds','A common mistake','Quick Q&A']],['Interactive Content',['Poll','Question of the week','True or false']],['Trust & Credibility',['The team','Vets and engineers','Production quality','Stories from the farm']]],calendarTitle:'Weekly Content Calendar',calendarIntro:'A proposed rhythm balancing education, engagement, and trust.',days:[['Saturday','Educational Post'],['Sunday','Story Poll'],['Monday','Behind-the-Scenes Reel'],['Tuesday','Quick Tip'],['Wednesday','Q&A Story'],['Thursday','Educational Carousel'],['Friday','Community / Light Content']],skillsTitle:'Skills I Bring to the Role',skillsIntro:'Tools that serve the idea, from understanding a topic to presenting it visually.',skills:['Practical Animal Production Knowledge','Technical Content Simplification','UI/UX','GIMP','AI Tools','Content Ideation','Visual Content','HTML / CSS / JavaScript','Responsive Design','Git / GitHub'],aboutTitle:'About Me',about:['I am an Animal Production graduate with practical experience in dairy farming, milking operations, herd health monitoring, and production quality.','I later moved into web development, where I gained experience in interface design, user experience, digital content, and AI tools.','I believe combining agricultural knowledge with digital skills can help me create social media content that is more accurate, engaging, and relevant to the target audience.'],honest:'This concept portfolio demonstrates skills I can bring to the role; it does not claim previous professional experience with the title Social Media Specialist.',profileAlt:'Placeholder for a portrait of Tarek Ibrahim Abdullah',profileLabel:'Animal production × Digital content',finalTitle:'I Understand the Industry — and I Have the Digital Tools to Present It Differently.',finalSub:'This portfolio is a practical concept showing how I can combine my experience in animal production, web development, and AI to create relevant digital content for Mazraaty.',contact:'Contact Me',contactPending:'Email coming soon. Contact details have not been added yet.',disclaimer:'This is an unofficial concept portfolio created specifically for a job application to Mazraaty and is not an official company project.',footer:'Tarek Ibrahim Abdullah · Concept portfolio',back:'Back to top'
}
};
const AI_PROMPT='Cinematic early morning dairy farm in Egypt, healthy dairy cows, clean modern milking environment, warm natural sunlight, authentic agricultural atmosphere, professional commercial photography, realistic documentary style.';
// CONTACT PLACEHOLDER: insert your email here when ready, e.g. name@example.com.
const CONTACT_EMAIL='';
const navIds=['home','content','reel','ideas','about'];
const escapeHTML=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const listHTML=items=>`<ul>${items.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`;
const heading=(n,title,intro)=>`<div class="section-heading"><span class="section-number" aria-hidden="true">${n}</span><div><h2>${title}</h2>${intro?`<p>${intro}</p>`:''}</div></div>`;
function buildPage(lang){const t=translations[lang];return `
<a class="skip-link" href="#main">${t.skip}</a>
<header class="site-header"><div class="container header-inner"><a class="wordmark" href="#home"><span class="brand-mark" aria-hidden="true">T<span>.</span></span><span>${t.shortName}<small>${t.portfolio}</small></span></a><nav class="navigation" id="navigation" aria-label="${t.portfolio}">${navIds.map((id,i)=>`<a href="#${id}" ${i===0?'aria-current="location"':''}>${t.nav[i]}</a>`).join('')}</nav><div class="header-controls"><div class="language-switch" role="group" aria-label="${t.language}" dir="ltr"><button type="button" data-lang="ar" aria-pressed="${lang==='ar'}" lang="ar" aria-label="العربية">AR</button><span aria-hidden="true">|</span><button type="button" data-lang="en" aria-pressed="${lang==='en'}" lang="en" aria-label="English">EN</button></div><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation" aria-label="${t.menu}"><span></span><span></span><span></span></button></div></div></header>
<main id="main"><section class="hero" id="home"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">${t.label}</p><p class="application">${t.application}</p><p class="hero-name">${t.name}</p><h1>${t.hero}</h1><p class="hero-intro">${t.intro}</p><div class="button-row"><a class="button button-primary" href="#content">${t.explore}</a><a class="button button-outline" href="#reel">${t.viewReel}</a></div><div class="hero-tags">${t.heroTags.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="hero-visual"><div class="visual-topline"><span>${t.concept}</span><span aria-hidden="true" dir="ltr">${t.fieldTag}</span></div><!-- Replace with an authentic dairy farm photograph or original farm/content moodboard. --><img src="assets/images/profile/hero-placeholder.svg" width="640" height="640" alt="${t.visualAlt}" fetchpriority="high"><div class="visual-copy"><span class="mini-label">${t.posts[0].tag}</span><h2>${t.visualTitle}</h2><p>${t.visualSub}</p></div><div class="visual-footer"><span>${t.profileLabel}</span><span aria-hidden="true">01 / 04</span></div></div></div></section>
<section class="section" id="fit"><div class="container">${heading('01',t.fitTitle,t.fitIntro)}<div class="fit-grid">${t.fit.map((f,i)=>`<article class="fit-card reveal"><span class="card-index" aria-hidden="true">0${i+1}</span><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div></div></section>
<section class="section section-tint" id="content"><div class="container">${heading('02',t.samplesTitle,t.samplesIntro)}<div class="posts-grid">${t.posts.map((p,i)=>`<article class="post-card reveal"><div class="post-visual tone-${i}"><div class="post-top"><span>${t.sampleLabel}</span><span dir="ltr">0${i+1}</span></div><!-- Replace with ${['dairy cow heat stress educational post image','authentic behind-the-scenes farm and milking photo','udder hygiene educational carousel graphic','milk production quick tip graphic'][i]}. --><img src="assets/images/posts/post-${i+1}.svg" width="800" height="650" loading="lazy" alt="${p.alt}"><div class="post-cover"><span class="mini-label">${p.tag}</span><h3>${p.cover}</h3><p>${p.coverSub}</p></div><div class="post-bottom"><span>${t.shortName}</span><span aria-hidden="true">${i===1?'▶':'▤'}</span></div></div><div class="post-body"><h3>${p.title}</h3><dl class="post-meta"><div><dt>${t.format}</dt><dd>${p.format}</dd></div><div><dt>${t.objective}</dt><dd>${p.objective}</dd></div></dl><div class="caption"><h4>${t.caption}</h4><p>${p.lead}</p>${p.pre?`<p>${p.pre}</p>`:''}${listHTML(p.list)}${p.end?`<p>${p.end}</p>`:''}</div><p class="post-cta"><span>${t.action}</span>${p.cta}</p></div></article>`).join('')}</div></div></section>
<section class="section reel-section" id="reel"><div class="container">${heading('03',t.reelTitle,t.reelIntro)}<div class="reel-layout"><div class="reel-preview"><!-- Replace with the opening frame of the 20–30 second dairy farm Reel. --><img src="assets/images/reel/reel-placeholder.svg" width="540" height="960" loading="lazy" alt="${t.reelAlt}"><span class="reel-badge">${t.aiLabel}</span><div class="reel-preview-copy"><span class="mini-label">${t.duration}</span><p>${t.hook}</p><button type="button" class="play-button" data-open-reel><span class="play-icon" aria-hidden="true">▶</span>${t.play}</button></div></div><div class="reel-info"><h3>${t.reelName}</h3><p class="preview-note">${t.previewNote}</p><div class="storyboard">${t.scenes.map((s,i)=>`<article class="scene-card reveal"><span class="scene-time" dir="ltr">${String(i*5).padStart(2,'0')}–${String((i+1)*5).padStart(2,'0')}s</span><h4>${t.scene} ${i+1}</h4><p>${s[0]}</p><blockquote>${s[1]}</blockquote></article>`).join('')}</div><div class="prompt-box"><h4>${t.promptTitle}</h4><p lang="en" dir="ltr">${AI_PROMPT}</p></div></div></div></div></section>
<section class="section section-tint" id="stories"><div class="container">${heading('04',t.storiesTitle,t.storiesIntro)}<div class="stories-grid">${t.stories.map((s,i)=>`<article class="story-phone story-${i} reveal"><!-- Replace with ${['a dairy cow photo for a heat stress quiz Story','a farm-life photo for the content preference poll','a calm dairy herd photo for the Q&A Story'][i]}. --><img src="assets/images/stories/story-${i+1}.svg" width="450" height="800" alt="${t.storyAlt}" loading="lazy"><div class="story-ui"><div class="story-progress" aria-hidden="true"><span></span><span></span><span></span></div><div class="story-author"><span class="story-avatar" aria-hidden="true">T.</span><span>${t.shortName}<small>${t.concept}</small></span></div><div class="story-content"><span class="story-count" aria-hidden="true">0${i+1}</span><h3>${s[0]}</h3><div class="story-sticker"><p>${s[1]}</p>${s[2].length?`<div class="story-options">${s[2].map((o,j)=>`<button type="button" data-story="${i}" data-choice="${j}" aria-pressed="false">${o}</button>`).join('')}</div>`:`<form id="question-form"><label class="sr-only" for="story-question">${s[0]}</label><input id="story-question" type="text" maxlength="180" placeholder="${t.questionPlaceholder}" autocomplete="off"><button class="question-submit" type="submit">${t.send}</button></form>`}</div><p class="story-result" id="story-result-${i}" aria-live="polite"></p></div></div></article>`).join('')}</div></div></section>
<section class="section" id="ideas"><div class="container">${heading('05',t.strategyTitle,t.strategyIntro)}<div class="pillars-grid">${t.pillars.map((p,i)=>`<article class="pillar reveal"><span class="pillar-number" aria-hidden="true">0${i+1}</span><h3>${p[0]}</h3>${listHTML(p[1])}</article>`).join('')}</div></div></section>
<section class="section calendar-section" id="calendar"><div class="container">${heading('06',t.calendarTitle,t.calendarIntro)}<ol class="calendar-grid">${t.days.map((d,i)=>`<li class="calendar-day reveal"><span class="day-index" aria-hidden="true">0${i+1}</span><h3>${d[0]}</h3><p>${d[1]}</p><span class="calendar-line" aria-hidden="true"></span></li>`).join('')}</ol></div></section>
<section class="section" id="skills"><div class="container">${heading('07',t.skillsTitle,t.skillsIntro)}<ul class="skills-list">${t.skills.map(s=>`<li>${s}</li>`).join('')}</ul></div></section>
<section class="section section-tint" id="about"><div class="container about-grid"><div class="about-portrait"><!-- Replace with a professional portrait of Tarek Ibrahim Abdullah. --><img src="assets/images/profile/portrait-placeholder.svg" width="600" height="700" loading="lazy" alt="${t.profileAlt}"><div class="portrait-caption"><h3>${t.name}</h3><p>${t.profileLabel}</p></div></div><div class="about-copy">${heading('08',t.aboutTitle,'')}${t.about.map(p=>`<p>${p}</p>`).join('')}<p class="honesty-note">${t.honest}</p></div></div></section>
<section class="section final-cta" id="contact"><div class="container final-inner"><p class="eyebrow">${t.label}</p><h2>${t.finalTitle}</h2><p>${t.finalSub}</p><!-- CONTACT PLACEHOLDER: add your email to CONTACT_EMAIL in js/main.js. --><button class="button button-light" id="contact-button" type="button">${t.contact}</button><p id="contact-status" class="contact-status" role="status"></p></div></section></main>
<footer class="site-footer"><div class="container"><p class="disclaimer">${t.disclaimer}</p><div class="footer-bottom"><span>${t.footer}</span><a href="#home">${t.back}</a></div></div></footer>
<dialog id="reel-modal" aria-labelledby="modal-title"><div class="modal-header"><h2 id="modal-title">${t.reelName}</h2><button type="button" class="modal-close" aria-label="${t.close}">×</button></div><p class="modal-note">${t.previewNote}</p><div class="modal-stage"><img src="assets/images/reel/reel-placeholder.svg" width="540" height="960" alt=""><span class="modal-scene-number"></span><div class="modal-frame"><p class="modal-visual"></p><h3 class="modal-caption"></h3></div></div><div class="playback-track" role="progressbar" aria-label="${t.play}" aria-valuemin="0" aria-valuemax="30" aria-valuenow="0"><span></span></div><div class="playback-controls"><span class="playback-time" dir="ltr">00 / 30s</span><button type="button" id="pause-reel">${t.pause}</button><button type="button" id="replay-reel">${t.replay}</button></div></dialog>`;
}
if(typeof module!=='undefined'&&module.exports)module.exports={translations,buildPage};
if(typeof document!=='undefined'){
let currentLanguage='ar',revealObserver,navObserver,timer,frame=0,paused=false,lastFocus;
const root=document.getElementById('page');
const storage={get(){try{return localStorage.getItem('portfolio-language');}catch{return null;}},set(lang){try{localStorage.setItem('portfolio-language',lang);}catch{/* Switching still works with storage blocked. */}}};
function stopTimer(){clearInterval(timer);timer=null;}
function renderLanguage(lang,save=false){
const oldY=window.scrollY,focusedLanguage=document.activeElement?.dataset?.lang;
stopTimer();revealObserver?.disconnect();navObserver?.disconnect();currentLanguage=lang;
document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';root.innerHTML=buildPage(lang);document.body.classList.remove('modal-open');const t=translations[lang];document.title=t.title;
document.querySelector('meta[name="description"]').content=t.description;document.querySelector('meta[property="og:title"]').content=t.title;document.querySelector('meta[property="og:description"]').content=t.description;document.querySelector('meta[property="og:locale"]').content=lang==='ar'?'ar_EG':'en_US';document.querySelector('meta[property="og:locale:alternate"] ').content=lang==='ar'?'en_US':'ar_EG';
document.querySelector('meta[property="og:locale:alternate"] ').content=lang==='ar'?'en_US':'ar_EG';bindInteractions();if(save)storage.set(lang);if(focusedLanguage)root.querySelector(`[data-lang="${focusedLanguage}"]`)?.focus({preventScroll:true});if(save)window.scrollTo({top:oldY,behavior:'instant'});
}
function bindInteractions(){
const t=translations[currentLanguage];root.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>renderLanguage(b.dataset.lang,true)));
const menu=root.querySelector('.menu-toggle'),nav=root.querySelector('.navigation');
const closeMenu=()=>{menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label',t.menu);nav.classList.remove('is-open');};
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?t.closeMenu:t.menu);nav.classList.toggle('is-open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));nav.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();menu.focus();}});
if('IntersectionObserver'in window){
revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target);}}),{threshold:.08});root.querySelectorAll('.reveal').forEach(e=>revealObserver.observe(e));
navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)nav.querySelectorAll('a').forEach(a=>{if(a.hash===`#${e.target.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}),{rootMargin:'-15% 0px -55% 0px',threshold:0});navIds.forEach(id=>navObserver.observe(document.getElementById(id)));
}else root.querySelectorAll('.reveal').forEach(e=>e.classList.add('is-visible'));
root.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.story),j=Number(b.dataset.choice);b.closest('.story-options').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(b===x)));document.getElementById(`story-result-${i}`).textContent=i===0?(j===0?t.answerTrue:t.answerFalse):t.vote;}));
document.getElementById('question-form').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('story-question'),out=document.getElementById('story-result-2');out.textContent=input.value.trim()?`${input.value.trim()} — ${t.questionSaved}`:t.questionEmpty;});
document.getElementById('contact-button').addEventListener('click',()=>{if(CONTACT_EMAIL)window.location.href=`mailto:${CONTACT_EMAIL}`;else document.getElementById('contact-status').textContent=t.contactPending;});
const dialog=document.getElementById('reel-modal');root.querySelector('[data-open-reel]').addEventListener('click',()=>{lastFocus=root.querySelector('[data-open-reel]');frame=0;paused=false;document.getElementById('pause-reel').disabled=false;dialog.showModal();document.body.classList.add('modal-open');updateFrame();startTimer();});
dialog.querySelector('.modal-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{stopTimer();document.body.classList.remove('modal-open');lastFocus?.focus({preventScroll:true});});
document.getElementById('pause-reel').addEventListener('click',()=>{if(frame>=30)return;paused=!paused;paused?stopTimer():startTimer();document.getElementById('pause-reel').textContent=paused?t.resume:t.pause;});document.getElementById('replay-reel').addEventListener('click',()=>{frame=0;paused=false;document.getElementById('pause-reel').disabled=false;updateFrame();startTimer();});
}
function updateFrame(){const t=translations[currentLanguage],i=Math.min(Math.floor(frame/5),5),dialog=document.getElementById('reel-modal');dialog.querySelector('.modal-scene-number').textContent=`${t.scene} ${i+1} / 6`;dialog.querySelector('.modal-visual').textContent=t.scenes[i][0];dialog.querySelector('.modal-caption').textContent=t.scenes[i][1];dialog.querySelector('.playback-time').textContent=`${String(frame).padStart(2,'0')} / 30s`;dialog.querySelector('.playback-track').setAttribute('aria-valuenow',String(frame));dialog.querySelector('.playback-track span').style.width=`${frame/30*100}%`;document.getElementById('pause-reel').textContent=paused?t.resume:t.pause;if(frame>=30){stopTimer();document.getElementById('pause-reel').disabled=true;}}
function startTimer(){stopTimer();timer=setInterval(()=>{frame++;updateFrame();},1000);}
renderLanguage(storage.get()==='en'?'en':'ar');
// Shared listeners are bound once, not once per language switch.
document.addEventListener('click',e=>{const nav=document.getElementById('navigation'),menu=document.querySelector('.menu-toggle');if(nav?.classList.contains('is-open')&&!e.target.closest('.header-inner')){nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label',translations[currentLanguage].menu);}});
window.addEventListener('resize',()=>{if(window.innerWidth>=900){document.getElementById('navigation')?.classList.remove('is-open');const menu=document.querySelector('.menu-toggle');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label',translations[currentLanguage].menu);}});
}


